import type { Metadata } from "next";
import "../assets/globals.css";


export const metadata: Metadata = {
  title: "OralTech",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}

      
      </body>
    </html>
  );
}
